### ISSUE TITLE
Double entries in stereotype export

### ISSUE THREAD

**Issue by MarkusAndres** [GfSE/SAF-Specification#36]
There are SAF_SCV02a_View and SAF_SCV02b_View entries available in the CSV export of the stereotypes. In my opinion SAF_SCV02b_View should be deleted as a entry. (see "stereotypes.csv" https://github.com/GfSE/SAF-Specification/blob/main/stereotypes.csv)

**Comment by haarer** [comment]
this is a problem caused by the markdown generator, it did not write the documentation of the grid viewpoint into that stereotype SAF_SCV02b_View.
( because the generator doesnt handle the case when a stereotype implements both a viewpoint and concepts)

Since the Grid Viewpoint is in the state "proposed" please just ignore the SAF_SCV02b_View stereotype.

**Comment by haarer** [comment]
documentation and generator fixed, stereotype stays.
