### ISSUE TITLE
Request for Dependency Stereotype

### ISSUE THREAD

**Issue by parkaneric** [GfSE/SAF-Specification#71]
[Common Standards Definition Viewpoint](https://saf.gfse.org/userdoc/Common%20Domain/Common%20Standards%20Definition%20Viewpoint.html)

**Request for Dependency Stereotype**
The standard stereotype will also be used to document (legal) norms. As norms have dependencies amongst each other, a dedicated stereoytpe is requested to reveal them. An additional note or rational might also be helpful to highlight/explain the dependency in more detail.
Please define a particular dependency stereotype for this purpose.

**Comment by haarer** [comment]
Does this mean that the concern is, to document a dependency among standards because if one standard is required to be applied the dependency means that the other standard must also be applied ? 
What is the intended semantics of the relation and what is the use case ? 

If there is an information need (a concern) then there should also be a rationale of a stakeholder, which explains why this is important.

**Comment by haarer** [comment]
I think that this could be a valid example. The SE handbooks refer to the ISO processes, thus depend on the standard.
Same with the NIST Publication, which explicitly adds content to the technical processes.
![grafik](https://github.com/user-attachments/assets/2862c074-886d-42ed-968f-e731ed748063)

**Comment by haarer** [comment]
done
